//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalAssignment__APWDN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int likeId { get; set; }
        public int postId { get; set; }
        public int userId { get; set; }
    
        public Post Post { get; set; }
        public User User { get; set; }
    }
}
